version: '0.1.0'
services:
  ros-base:
    build:
      dockerfile: ./dockers/ros-base.dockerfile
    image: ros-base
    stdin_open: true
    tty: true
    environment:
      - DISPLAY=$DISPLAY
      - QT_X11_NO_MITSHM=1
    privileged: true
    entrypoint: bash
    network_mode: host
  ros-and-rust:
    build:
      dockerfile: ./dockers/ros-and-rust.dockerfile
    depends_on:
      - ros-base
    image: ros-and-rust
    stdin_open: true
    tty: true
    environment:
      - DISPLAY=$DISPLAY
      - QT_X11_NO_MITSHM=1
    privileged: true
    entrypoint: bash
    network_mode: host
  dev:
    build:
      dockerfile: ./dockers/dev.dockerfile
    image: dev
    depends_on:
      - ros-and-rust
    stdin_open: true
    tty: true
    environment:
      - DISPLAY=$DISPLAY
      - QT_X11_NO_MITSHM=1
    privileged: true
    volumes:
      - .:/home/user/workspace/zenoh-bridge-dds-test
    network_mode: host
    working_dir: /home/user/workspace/zenoh-bridge-dds-test
    entrypoint: /home/user/workspace/zenoh-bridge-dds-test/scripts/dev.sh
    # networks:
    #   - local
    #   # local:
    #   #   ipv4_address: 192.168.0.2

# networks:
#   local:
#     driver: bridge
#     ipam:
#       driver: default
#       config:
#         - subnet: 192.168.0.1/16
