version: '0.1.0'
services:

  build-ros-base:
    build:
      dockerfile: ./dockers/ros-base.dockerfile
    image: ros-base

  build-ros-and-rust:
    build:
      dockerfile: ./dockers/ros-and-rust.dockerfile
    image: ros-and-rust
    depends_on:
      - build-ros-base

  build-dev:
    build:
      dockerfile: ./dockers/dev.dockerfile
    image: dev
    depends_on:
      - build-ros-and-rust

  build-pubsub-test:
    build:
      dockerfile: ./dockers/pubsub-test.dockerfile
    image: pubsub-test
    depends_on:
      - build-ros-and-rust

  pubsub-test:
    image: pubsub-test
    stdin_open: true
    tty: true
    environment:
      - DISPLAY=$DISPLAY
      - QT_X11_NO_MITSHM=1
    privileged: true
    working_dir: /home/user/workspace/zenoh-plugin-dds-test
    entrypoint: bash

  dev-base:
    depends_on:
      - build-dev
    image: dev
    stdin_open: true
    tty: true
    environment:
      - DISPLAY=$DISPLAY
      - QT_X11_NO_MITSHM=1
    privileged: true
    volumes:
      - .:/home/user/workspace/zenoh-plugin-dds-test
    working_dir: /home/user/workspace/zenoh-plugin-dds-test
    entrypoint: /home/user/workspace/zenoh-plugin-dds-test/scripts/dev.sh

  dev-network-host:
    extends: dev-base
    network_mode: host

  dev-network-bridge:
    extends: dev-base
    dns:
      - 8.8.8.8
    networks:
      local:
        ipv4_address: 193.168.0.5

  dev-network-NAT1:
    extends: dev-base
    networks:
      - local
      - N1

  dev-network-NAT2:
    extends: dev-base
    networks:
      - local
      - N2

  # C1:
  #   build:
  #     dockerfile: ./dockers/dev.dockerfile
  #   image: dev
  #   depends_on:
  #     - ros-and-rust
  #   stdin_open: true
  #   tty: true
  #   environment:
  #     - DISPLAY=$DISPLAY
  #     - QT_X11_NO_MITSHM=1
  #   privileged: true
  #   volumes:
  #     - .:/home/user/workspace/zenoh-plugin-dds-test
  #   working_dir: /home/user/workspace/zenoh-plugin-dds-test
  #   entrypoint: /home/user/workspace/zenoh-plugin-dds-test/scripts/dev.sh
  #   # network_mode: host
  #   dns:
  #     - 8.8.8.8
  #   networks:
  #   - N1

networks:
  local:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 193.168.0.1/8
  N1:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 173.34.0.0/8
  N2:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 153.35.0.0/8
  # N2:
  #   driver: bridge
  #   ipam:
  #     driver: default
  #     config:
  #       - subnet: 192.168.0.1/16
